// JavaScript for updating card content
$(document).ready(function () {
    var cardContents = {
        Stories:{
            header: "Stories",
            content:[
            "Share a personal experience of feeling God's presence during a difficult time.",
"Describe a story you've heard about someone feeling a tangible connection to God.",
"Tell a personal story about facing a challenge to your faith and how you navigated it.",
"Share an anecdote about witnessing God's provision in your life, or someone else's.",
"Reflect on how your understanding of God evolved over time.",
"Describe a situation where you or someone you know felt compelled to take a leap of faith.",
"Share a personal story about experiencing profound love from God.",
"Tell an anecdote about experiencing the power of prayer in your life, or someone else's.",
"Reflect on how serving others deepened your faith, or someone else's.",
"Describe a situation where you or someone you know felt guided by God in a decision.",
"Share a personal story of witnessing a miraculous event, or hearing about one.",
"Describe a moment of communal faith experience you've had, or heard about.",
"Tell a personal story or one you've heard about reconciliation between individuals or groups.",
"Share an anecdote about feeling overwhelmed by God's grace in your life, or someone else's.",
"Reflect on how you or someone else felt called to a new purpose in life.",
"Describe a moment when you or someone else experienced a breakthrough in their faith journey.",
"Share a personal story or one you've heard about experiencing God's faithfulness.",
"Tell an anecdote about finding peace amidst difficult circumstances.",
"Reflect on a personal experience or one you've heard about a powerful answer to prayer.",
"Describe a moment when you or someone else felt connected to God through nature.",
"Share a personal story about experiencing personal growth through faith.",
"Describe a moment of corporate worship where God's presence was strongly felt by you or someone you know.",
"Tell a personal story or one you've heard about feeling prompted to share faith with others.",
"Reflect on how you or someone else found comfort in God during a time of loss.",
"Share a personal story or one you've heard about experiencing the journey of forgiveness.",
"Describe a situation where you or someone else witnessed God's unexpected intervention.",
"Tell a personal story about experiencing joy in your faith journey or someone else's.",
"Reflect on a moment when you or someone else felt renewed purpose in their faith.",
"Share a personal story or one you've heard of seeing God turn a difficult situation into something good.",
"Describe a moment of gratitude towards God in your life or someone else's.",
"Share a personal story about feeling strengthened by God during a challenge.",
"Reflect on a time when you or someone else found guidance and comfort in Scripture.",
"Describe a moment of healing experienced by you or someone else through their faith.",
"Share a personal story or one you've heard about stepping out of a comfort zone in faith.",
"Tell a personal story about experiencing God's presence in celebration.",
"Reflect on how you or someone else witnessed God's love through the actions of others.",
"Describe a moment of peace found amidst chaos through your faith or someone else's.",
"Share a personal story or one you've heard about experiencing provision through the kindness of others.",
"Reflect on a personal story or one you've heard of making a significant life change guided by faith.",
"Describe a moment of worship where you or someone else felt a profound sense of God's presence."
        ]},
        Interpretations:{
            header: "Interpretations",
            content:[
            "What does grace mean to you personally?",
        "How do you understand the concept of forgiveness in Christianity?",
        "What does it mean to love your neighbor as yourself?",
        "How do you interpret the role of faith in everyday life?",
        "What does it mean to be a disciple of Christ?",
        "How do you understand the concept of salvation?",
        "What does it mean to have a personal relationship with God?",
        "How do you interpret the Bible's teachings on prayer?",
        "What role does worship play in your spiritual life?",
        "How do you interpret the concept of the Trinity?",
        "What does it mean to live a holy life?",
        "How do you understand the concept of sin?",
        "What is the significance of baptism in Christianity?",
        "How should Christians approach the topic of suffering?",
        "What does it mean to follow Jesus?",
        "How do you understand the concept of the Kingdom of God?",
        "What is the importance of the Bible in the Christian faith?",
        "How should Christians view the end times?",
        "What does it mean to be filled with the Holy Spirit?",
        "How should Christians approach the topic of spiritual gifts?",
        "What is the role of the church in the Christian life?",
        "How do you interpret the Bible's teachings on marriage?",
        "What does it mean to be a witness for Christ?",
        "How should Christians understand the concept of predestination?",
        "How do you interpret the creation story in Genesis?",
        "What is the Christian view of angels and demons?",
        "How should Christians understand the concept of atonement?",
        "What does it mean to have faith like a child?",
        "How do you interpret the Bible's teachings on heaven and hell?",
        "What is the Christian view of the afterlife?",
        "How should Christians understand the concept of God's sovereignty?",
        "What does it mean to be a servant leader?",
        "How should Christians understand the concept of the church as the body of Christ?",
        "What does it mean to be called by God?",
        "How should Christians understand the concept of spiritual warfare?",
        "What is the significance of the Ten Commandments for Christians?",
        "How should Christians understand the concept of free will?",
        "What does it mean to have faith in God's promises?",
        "How should Christians understand the concept of the second coming of Christ?",
        "What is the Christian view of the Great Commission?"
        ]},
        IceBreaker:{
            header: "IceBreaker",
            content:[
            "If Jesus were alive today, what social media platform do you think he'd use most?",
            "Which Biblical character would throw the best party, and why?",
            "If you could trade places with any Biblical character for a day, who would it be and why?",
            "Which Biblical character would make the best superhero, and what would their powers be?",
            "If you could witness any Biblical event firsthand, which one would you choose?",
            "Which Biblical character would be the most likely to win a modern-day talent show, and what would their talent be?",
            "If you could have a one-on-one conversation with any Biblical character, who would it be and what would you talk about?",
            "Which Biblical character's life would make the most interesting biopic movie?",
            "If you could receive a letter from any Biblical character, who would you want it to be from and what would it say?",
            "Which Biblical character would you want as a mentor, and why?",
            "If you could swap lives with a Bible character for a week, who would it be and what would you do?",
            "Which Biblical character do you think would be the best at solving modern-day problems, and why?",
            "If you could invite a Biblical character to a modern-day dinner party, who would you choose and why?",
            "Which Biblical character would make the best travel companion, and where would you go?",
            "If you could witness any conversation between two Biblical characters, which one would it be?",
            "Which Biblical character's wisdom do you admire the most?",
            "If you could be roommates with any Bible character, who would you choose and why?",
            "Which Biblical character would have the best Instagram stories, and what would they share?",
            "If you could spend a day with any Biblical character, how would you spend it?",
            "Which Biblical character's life would make the most captivating podcast series, and why?",
            "If you could ask one Biblical character any question, who would it be and what would you ask?",
            "Which Biblical character would have the most fascinating autobiography, and why?",
            "If you could see a modern-day adaptation of any Biblical story, which one would you choose?",
            "Which Biblical character would you want as a teammate in a scavenger hunt, and why?",
            "If you could give a gift to any Biblical character, what would it be and why?",
            "Which Biblical character's personality do you relate to the most?",
            "If you could introduce a Biblical character to a modern-day hobby, what would it be?",
            "Which Biblical character would be the best at giving TED talks, and what topic would they speak on?",
            "If you could receive advice from any Biblical character, who would you want advice from and what would you ask?",
            "Which Biblical character's life story inspires you the most?",
            "If you could have a meal with any Biblical character, who would you choose and why?",
            "Which Biblical character would you want as a co-worker, and why?",
            "If you could witness any miracle from the Bible, which one would you choose?",
            "Which Biblical character would throw the best surprise party, and who would they throw it for?",
            "If you could learn a skill from any Biblical character, what skill would it be and who would you learn from?",
            "Which Biblical character's daily routine would you most want to experience?",
            "If you could attend a concert with any Biblical character, who would you choose and what music would you listen to?",
            "Which Biblical character do you think would be the best at social media, and why?",
            "If you could accompany any Biblical character on a journey, who would you choose and where would you go?",
            "Which Biblical character's advice would you want to receive before making a big decision?"

        ]},
        HotTopics:{
            header:"HotTopics",
            content: [
            "Should Christians participate in politics?",
            "How should Christians respond to societal issues like poverty and inequality?",
            "Is it okay for Christians to have doubts about their faith?",
            "Should the church play a role in environmental activism?",
            "What are your thoughts on the intersection of faith and mental health?",
            "Should Christians support the death penalty?",
            "How should Christians approach issues of sexuality and gender identity?",
            "Is it possible to reconcile science and faith?",
            "Should Christians prioritize missions work over local community outreach?",
            "How should Christians navigate the use of social media and technology?",
            "Should Christians be involved in social justice movements?",
            "Is there a conflict between faith and reason?",
            "Should Christians be concerned about climate change?",
            "How should Christians address racial injustice?",
            "Should Christians tithe?",
            "Is it important for Christians to evangelize?",
            "Should Christians be pacifists?",
            "How should Christians respond to immigration issues?",
            "Is there a place for art and creativity in Christianity?",
            "How should Christians view wealth and material possessions?",
            "Should Christians be involved in the entertainment industry?",
            "How should Christians approach the topic of war?",
            "Is there a place for doubt in the Christian faith?",
            "How should Christians address homelessness?",
            "Should Christians prioritize environmental conservation?",
            "Is it important for Christians to engage in interfaith dialogue?",
            "How should Christians respond to addiction and substance abuse?",
            "Should Christians support the LGBTQ+ community?",
            "Is there a Christian perspective on healthcare?",
            "How should Christians approach issues of immigration?",
            "Should Christians engage in civil disobedience?",
            "How should Christians respond to political corruption?",
            "Should Christians be concerned about consumerism?",
            "Is it important for Christians to practice forgiveness?",
            "Should Christians be involved in advocating for human rights?",
            "How should Christians view technology and artificial intelligence?",
            "Should Christians be concerned about globalization?",
            "Is there a Christian perspective on animal rights?",
            "How should Christians approach issues of wealth and poverty?",
            "Should Christians be involved in education reform?",
            "What is the correct chritian view of marriage, divorce and remarriage.",
            "What if any are the biblical roles of men and women?",
            "Must i go to church?",
            "How do you know God's voice?",
            "What do you consider a red flag during courtship or a relationship",
            "Do we have free will or everything is predestined",
            "Is it okay for christians to perfom beauty enhancing surgeries?",
        ]},
        Apologetics:{
            header: "Apologetics",
            content:[
                "How would you defend the existence of God to someone who is skeptical?",
"What evidence do you find most compelling for the truth of your faith?",
"How do you respond to common objections against the reliability of religious texts?",
"What philosophical arguments support the idea of a divine creator?",
"How would you explain the problem of evil and suffering in the context of your faith?",
"What historical evidence exists for the life and teachings of key figures in your faith tradition?",
"How do you reconcile scientific discoveries with your religious beliefs?",
"What role does faith play in your understanding of truth and knowledge?",
"How would you respond to someone who claims that religion is just a product of human imagination?",
"What is your perspective on the relationship between faith and reason?",
"How do you address questions about the exclusivity of salvation in your faith?",
"What evidence exists for the resurrection of Jesus Christ, and how do you defend it?",
"How would you explain the concept of miracles to someone who is skeptical?",
"What philosophical arguments support the idea of an afterlife?",
"How do you respond to claims that religious belief is irrational or delusional?",
"What role does personal experience play in your belief system, and how do you share it with others?",
"How would you respond to criticisms of religious institutions and their historical actions?",
"What is your perspective on the compatibility of faith and modern science?",
"How do you address questions about the reliability of religious experiences?",
"What evidence exists for the authenticity and transmission of religious teachings?",
"How do you reconcile apparent contradictions within religious texts?",
"What philosophical arguments support the existence of objective moral values?",
"How do you respond to claims that religious faith is harmful or divisive?",
"What role does prophecy fulfill in your understanding of religious truth?",
"How would you explain the concept of divine revelation to someone who is unfamiliar with it?",
"What historical evidence supports the claims of your faith regarding key events and figures?",
"How do you address questions about the problem of religious pluralism?",
"What is your perspective on the relationship between faith and doubt?",
"How would you respond to criticisms of religious faith as a form of wishful thinking?",
"What philosophical arguments support the idea of a moral lawgiver?",
"How do you address questions about the reliability of religious authorities and leaders?",
"What is your perspective on the role of faith in the search for meaning and purpose?",
"How do you respond to claims that religious belief is declining in the modern world?",
"What evidence exists for the fulfillment of prophecies within your faith tradition?",
"How would you explain the concept of divine sovereignty and human free will?",
"What is your perspective on the relationship between faith and personal identity?",
"How do you address questions about the compatibility of religion and contemporary ethics?",
"What is your perspective on the role of faith in addressing existential questions?",
"How would you respond to criticisms of religious faith as a form of intellectual stagnation?",
"What evidence exists for the transformative power of faith in individual lives and communities?",
"Are there things God cannot do? if so what are they and why.",
            ]},
        Ethics:{
            header:"Ethics",
            content:[
                "Is it ever justified to lie to protect someone's feelings?",
"Should society prioritize individual rights or the common good?",
"What ethical considerations should be taken into account in medical decision-making?",
"Is it ethical to use animals for scientific experimentation?",
"Should capital punishment be abolished?",
"What ethical responsibilities do individuals have towards the environment?",
"Is it ever acceptable to break a promise if it means preventing harm?",
"Should businesses prioritize profit or social responsibility?",
"What role should forgiveness play in addressing wrongdoing?",
"Is it ethical to redistribute wealth to address income inequality?",
"Should assisted suicide be legalized?",
"What ethical considerations should be taken into account in genetic engineering?",
"Is it ethical to use technology to enhance human abilities?",
"Should access to healthcare be considered a fundamental human right?",
"What ethical guidelines should govern the use of artificial intelligence?",
"Is it ever justifiable to engage in vigilantism?",
"Should affirmative action policies be implemented to address systemic discrimination?",
"What ethical responsibilities do individuals have towards future generations?",
"Is it ethical to prioritize one's own interests over the well-being of others?",
"Should recreational drug use be decriminalized?",
"What ethical considerations should be taken into account in international diplomacy?",
"Is it ethical to use surveillance technology to enhance security?",
"Should individuals have the right to end their own life if they are suffering?",
"What ethical guidelines should govern the use of artificial intelligence in warfare?",
"Is it ever acceptable to infringe on freedom of speech to prevent harm?",
"Should cultural practices that harm individuals be tolerated in the name of tradition?",
"What ethical responsibilities do individuals have towards refugees and migrants?",
"Is it ethical to profit from industries that harm the environment?",
"Should whistleblowers be protected or punished for exposing wrongdoing?",
"What ethical considerations should be taken into account in the use of data privacy?",
"Is it ethical to engage in nonviolent civil disobedience to protest injustice?",
"Should governments prioritize economic growth or environmental sustainability?",
"What ethical guidelines should govern the use of social media and digital platforms?",
"Is it ever justified to infringe on privacy rights in the name of national security?",
"Should individuals be held accountable for actions they commit under the influence of drugs or alcohol?",
"Is it ethical to impose cultural values on others through international intervention?",
"What ethical responsibilities do individuals have towards marginalized and vulnerable populations?",
"Should access to education be considered a fundamental human right?",
"Is it ethical to use technology to alter the genetic makeup of future generations?",
"What ethical considerations should be taken into account in the development and deployment of autonomous vehicles?"
            ]
        }

    };

    $('#updateCardContentBtn').click(function() {
        var categories = Object.keys(cardContents);
        var randomCategory = categories[Math.floor(Math.random() * categories.length)];
        var categoryContent = cardContents[randomCategory];
        var randomIndex = Math.floor(Math.random() * categoryContent.content.length);
        var newCardContent = categoryContent.content[randomIndex];
        $('#cardContent').html(`<p>${newCardContent}</p>`);
        $('#card').removeClass().addClass('card').addClass(randomCategory);
        $('#cardHeader').text(categoryContent.header);
    });
});